### PR TITLE
Perform in condition

### PR DESCRIPTION
**Pull request by unakatsuo**

### CODE REVIEW

**Comment by Metallion** [comment]
I wonder why travis CI isn't reporting to the pull requests automatically any more. Anyway, the tests all passed. https://travis-ci.org/axsh/sinatra-browse/builds/67491660

I will merge this and release a new version on Monday. I want to spend a little time checking if anything else has changed in master since the last version first.

**Comment by Metallion** [comment]
I was planning to merge this today but I took some more time to review it and study Sinatra conditions. Line 127 of this code deletes all user defined conditions. That needs to be fixed before we can merge this.

I have added a new rspec test to master that reproduces the issue. This test is currently green in master but will go red when merged in this branch.

Also, It's kind a dirty hack since the condition block wasn't meant to be used like this. I wonder if there is a better way. The goal of this PR is to solve the [named parameters in route](https://github.com/axsh/sinatra-browse#named-parameters-in-route-patterns) problem, right?

**Comment by unakatsuo** [comment]
Condition block is the right place to do validation. ``before`` block without path does not give us named parameters.

Even the last commit still has a ``__send__`` hack because sinatra-browse API design does not fit some part to sinatra.

Condition friendly API would be below:

```
sinatra_browse do
  param :xxxxx
  param :yyyy
end
get "/xxxx" do
end
```

This way requires less exposure with ``@_temp*`` variables.

**Comment by Metallion** [comment]
The Sinatra README clearly shows that *conditions* are intended to execute different routes depending on certain well... conditions. http://www.sinatrarb.com/intro.html#Conditions

Sinatra-browse is not deciding which route to execute. It is validating and transforming parameters.

I'm not saying that I'm against using the condition block like this but I am saying it feels a little hackish.

That condition friendly API looks interesting. The syntax is less pretty but it might offer a cleaner implementation. I might experiment with it a bit when I find the time.

**Comment by Metallion** [comment]
Looks like it still breaks user defined conditions. https://travis-ci.org/axsh/sinatra-browse/builds/67947241

**Comment by Metallion** [comment]
The tests are very red now. :(

`55 examples, 53 failures`

https://travis-ci.org/axsh/sinatra-browse/builds/67955422

**Comment by unakatsuo** [comment]
Continue to work in #18.

**Pull request closed without merging**
